- match:  /^[\s\S]+$/
  script:
    - time tnpm i dawn 
    - time dn config server 'https://query.aliyun-inc.com/rest/dc.service.cli?team=dawn&conf='
    - time dn config registry 'http://r.npm.alibaba-inc.com'
    - time dn test
    - time dn build

- match: master
  script:
    - time dn run ci-publish